version: "3.9"

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dog
      - POSTGRES_PASSWORD=woof
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
volumes:
  postgres:
    driver: local
